dubbo:
  application:
    name: provider
  registry:
    address: zookeeper://47.104.171.254:2181
    group: provider
  monitor:
    username: provider
    password: provider
    protocol: registry
  protocol:
    name: dubbo
    port: 8888

