dubbo:
  application:
    name: provider-2
  registry:
    address: zookeeper://47.104.171.254:2181
  monitor:
    username: provider
    password: provider
    protocol: registry
  protocol:
    name: dubbo
    port: 9092

server:
  port: 8083
